// =============================================================
// FPGA OCR Test-Vector Configuration
// =============================================================
//
// Automatically generated by python/export_test_vectors.py.
// Do not edit manually.
//

`ifndef TEST_VECTORS_VH
`define TEST_VECTORS_VH

`define NUM_TEST_IMAGES 2000
`define TEST_INPUT_SIZE 784
`define TOTAL_TEST_PIXELS 1568000

`endif
