`timescale 1ns/1ps

// =============================================================================
// Neural-Network Core Testbench
// =============================================================================
//
// Mixed-language simulation:
//
//     RTL       : VHDL
//     Testbench : Verilog
//
// The DUT implements the following sequential MNIST neural network:
//
//     784 binary pixels
//          |
//          v
//     Layer 1: 784 -> 64
//          |
//         ReLU
//          |
//          v
//     Layer 2: 64 -> 64
//          |
//         ReLU
//          |
//          v
//     Layer 3: 64 -> 32
//          |
//         ReLU
//          |
//          v
//     Layer 4: 32 -> 10
//          |
//          v
//        ArgMax
//          |
//          v
//     predicted_digit
//
// Only ONE image is processed at a time.
//
// =============================================================================
// Test Data
// =============================================================================
//
// Test vectors are stored under:
//
//     data/
//
// The testbench expects:
//
//     data/input_image.mem
//     data/expected_class.txt
//
// input_image.mem contains exactly 784 already-binarized pixels:
//
//     0
//     0
//     1
//     0
//     ...
//
// expected_class.txt contains the expected MNIST digit:
//
//     7
//
// These files should be generated from data/train.csv by the Python reference
// or vector-generation script.
//
// =============================================================================
// Layer 1 Optimization
// =============================================================================
//
// training.py converts every grayscale MNIST pixel to:
//
//     pixel <= 127 -> 0
//     pixel >  127 -> 1
//
// input_buffer.vhd therefore stores each of the 784 input pixels using only
// one bit.
//
// During Layer 1, nn_core configures:
//
//     dense_binary_input_mode = 1
//
// Therefore dense_layer.vhd replaces:
//
//     input * weight
//
// with:
//
//     input = 0 -> contribution = 0
//     input = 1 -> contribution = weight
//
// Layers 2 through 4 use normal signed fixed-point multiplication.
//
// =============================================================================

// Include the config file (e.g., containing the number of images)
`include "../config/test_vectors.vh"

module nn_core_tb;

    // =========================================================================
    // Configuration
    // =========================================================================

    // 50 MHz clock.
    localparam CLK_PERIOD = 20;

    // MNIST image dimensions:
    //
    //     28 x 28 = 784 pixels
    localparam INPUT_SIZE = 784;
    // Number of test images generated by export_test_vectors.py.
    //
    // The value comes from:
    //
    //     config/test_vectors.vh
    //
    localparam integer NUM_TEST_IMAGES = `NUM_TEST_IMAGES;

    // Total number of one-bit pixels stored in test_images.mem.
    localparam TOTAL_TEST_PIXELS = NUM_TEST_IMAGES * INPUT_SIZE;

    // Maximum number of cycles allowed for one complete inference.
    //
    // This prevents an RTL/FSM bug from causing an infinite simulation.
    localparam MAX_INFERENCE_CYCLES = 200000;

    // =========================================================================
    // Test File Paths
    // =========================================================================
    //
    // export_test_vectors.py generates:
    //
    //     data/test_images.mem
    //     data/test_labels.mem
    //
    // test_images.mem contains all binary MNIST images concatenated sequentially.
    //
    // test_labels.mem contains one expected digit for each image.
    //

    localparam TEST_IMAGES_FILE =
        "../../../data/test_images.mem";

    localparam TEST_LABELS_FILE =
        "../../../data/test_labels.mem";

    // =========================================================================
    // DUT Inputs
    // =========================================================================

    reg clk;
    reg rst;

    // One already-binarized MNIST pixel.
    reg pixel_in;

    // Indicates that pixel_in contains valid data.
    reg pixel_valid;

    // =========================================================================
    // DUT Outputs
    // =========================================================================

    // High while nn_core is ready to receive image pixels.
    wire input_ready;

    // Pulses high when predicted_digit contains a valid result.
    wire result_valid;

    // Predicted MNIST digit from 0 to 9.
    wire [3:0] predicted_digit;

    // =========================================================================
    // Test Vector Storage
    // =========================================================================
    //
    // All test images are stored in one contiguous memory.
    //
    // Organization:
    //
    //     image 0:
    //         image_memory[0 ... 783]
    //
    //     image 1:
    //         image_memory[784 ... 1567]
    //
    //     image 2:
    //         image_memory[1568 ... 2351]
    //
    //     ...
    //
    // Pixel address:
    //
    //     image_index * INPUT_SIZE + pixel_index
    //
    reg image_memory [0:TOTAL_TEST_PIXELS-1];
    // One expected MNIST digit is stored for every image.
    // Four bits are sufficient to represent classes 0 through 9.
    reg [3:0] expected_labels [0:NUM_TEST_IMAGES-1];
    // Index of the image currently being tested.
    integer test_index;
    // General-purpose pixel loop variable.
    integer pixel_index;
    // Index into the concatenated image memory.
    integer memory_index;
    // Number of correct classifications.
    integer pass_count;
    // Number of incorrect classifications.
    integer fail_count;
    // Number of cycles spent performing the current inference.
    integer inference_cycles;
    // Accumulated inference cycles over all images.
    integer total_inference_cycles;
    // Minimum observed inference latency.
    integer minimum_inference_cycles;
    // Maximum observed inference latency.
    integer maximum_inference_cycles;

    // Latency timestamps for the current image.
    time inference_start_time;
    time inference_end_time;
    time inference_latency;

    // Current-image latency converted to ns and us.
    real inference_latency_ns;
    real inference_latency_us;

    // Accumulated latency in microseconds.
    real total_latency_us;

    // =========================================================================
    // Device Under Test
    // =========================================================================

    nn_core dut (
        .clk             (clk),
        .rst             (rst),
        .pixel_in        (pixel_in),
        .pixel_valid     (pixel_valid),
        .input_ready     (input_ready),
        .result_valid    (result_valid),
        .predicted_digit (predicted_digit)
    );

    // =========================================================================
    // Clock Generator
    // =========================================================================

    initial begin
        clk = 1'b0;
        forever begin
            #(CLK_PERIOD / 2);
            clk = ~clk;
        end
    end

    // =========================================================================
    // Reset DUT
    // =========================================================================

    task reset_dut;
    begin
        rst = 1'b1;
        pixel_in = 1'b0;
        pixel_valid = 1'b0;

        // Keep reset asserted for five clock cycles.
        repeat (5)
            @(posedge clk);

        rst = 1'b0;

        // Allow nn_core to reach its input-ready state.
        repeat (2)
            @(posedge clk);
    end
    endtask

    // =========================================================================
    // Send One Binary Pixel
    // =========================================================================
    //
    // input_buffer.vhd stores pixel_in on a rising clock edge when pixel_valid
    // is asserted.
    //
    // pixel must already contain either:
    //
    //     0
    //
    // or:
    //
    //     1

    task send_pixel;
        input pixel;
    begin
        pixel_in = pixel;
        pixel_valid = 1'b1;

        @(posedge clk);

        pixel_valid = 1'b0;
    end
    endtask

    // =========================================================================
    // Send One Complete MNIST Image
    // =========================================================================
    //
    // Selects one image from the concatenated image_memory array and sends all
    // 784 binary pixels to the DUT.
    //
    // The first pixel for image N is located at:
    //
    //     N * INPUT_SIZE
    //
    // Therefore:
    //
    //     memory_index = image_index * INPUT_SIZE + pixel_index
    //
    task send_image;

        input integer image_index;

    begin
        // Wait until nn_core can accept a new image.
        while (!input_ready)
            @(posedge clk);

        // Send all 784 pixels belonging to this image.
        for (pixel_index = 0;pixel_index < INPUT_SIZE;pixel_index = pixel_index + 1)
        begin
            // Calculate this pixel's position in the single concatenated memory.
            memory_index = image_index * INPUT_SIZE + pixel_index;
            // Send the selected binary pixel.
            send_pixel(image_memory[memory_index]);
        end
    end
    endtask

    // =========================================================================
    // Wait for Classification
    // =========================================================================
    //
    // After the final input pixel is received, inference executes:
    //
    //     Layer 1
    //        |
    //        v
    //     Layer 2
    //        |
    //        v
    //     Layer 3
    //        |
    //        v
    //     Layer 4
    //        |
    //        v
    //      ArgMax
    //
    // Layer 1 uses the binary-input optimization.
    //
    // No second image is accepted during this sequence.

    task wait_for_result;
    begin
        inference_cycles = 0;

        while (!result_valid) begin
            @(posedge clk);

            inference_cycles = inference_cycles + 1;

            if (inference_cycles > MAX_INFERENCE_CYCLES) begin
                $display("");
                $display("ERROR: neural-network inference timeout");
                $display(
                    "Waited %0d cycles without result_valid",
                    inference_cycles
                );
                $fatal;
            end
        end
    end
    endtask

    // =========================================================================
    // Check Classification Result
    // =========================================================================
    //
    // Compares the FPGA result for one image against the corresponding expected
    // MNIST label.
    //
    // A classification error does not terminate the simulation.
    //
    // Instead, pass_count and fail_count are updated so that the complete test set
    // can be evaluated.
    //
    task check_result;

        input integer image_index;
        input [3:0] expected_digit_value;

    begin
        if (predicted_digit == expected_digit_value)
        begin
            pass_count = pass_count + 1;
            $display("Image %0d: PASS",image_index);
        end
        else
        begin
            fail_count = fail_count + 1;
            $display("Image %0d: FAIL",image_index);
        end

        $display("  Expected digit   : %0d",expected_digit_value);
        $display("  Predicted digit  : %0d",predicted_digit);
        $display("  Inference cycles : %0d",inference_cycles);
        $display("  Latency          : %0.3f us",inference_latency_us);
    end
    endtask

    // =========================================================================
    // Main Test Sequence
    // =========================================================================

    initial begin

        // ---------------------------------------------------------------------
        // Initialize Testbench Signals
        // ---------------------------------------------------------------------

        rst = 1'b0;
        pixel_in = 1'b0;
        pixel_valid = 1'b0;
        inference_cycles = 0;

        pass_count = 0;
        fail_count = 0;

        total_inference_cycles = 0;

        minimum_inference_cycles = MAX_INFERENCE_CYCLES;
        maximum_inference_cycles = 0;

        total_latency_us = 0.0;

        // ---------------------------------------------------------------------
        // Load All Binary MNIST Test Images
        // ---------------------------------------------------------------------
        //
        // Source:
        //
        //     data/test_images.mem
        //
        // The file contains all test images concatenated sequentially.
        //
        // Each image contains exactly:
        //
        //     784 binary pixels
        //
        // Therefore image N occupies:
        //
        //     N * INPUT_SIZE
        //
        // through:
        //
        //     N * INPUT_SIZE + INPUT_SIZE - 1
        //
        // Each line contains exactly one already-binarized pixel:
        //
        //     0
        //
        // or:
        //
        //     1
        //
        // The Python vector-generation script must use the same threshold as
        // training.py so that software and RTL receive identical input data.
        //
        $display("Loading test images from:");
        $display("  %s", TEST_IMAGES_FILE);

        $readmemb(
            TEST_IMAGES_FILE,
            image_memory
        );

        // ---------------------------------------------------------------------
        // Load All Expected MNIST Labels
        // ---------------------------------------------------------------------
        //
        // Source:
        //
        //     data/test_labels.mem
        //
        // One expected class is stored for each test image.
        //
        // Example:
        //
        //     7
        //     2
        //     1
        //     0
        //     ...
        //
        // The label at expected_labels[N] corresponds to image N in
        // image_memory.
        //
        $display("Loading expected labels from:");
        $display("  %s", TEST_LABELS_FILE);

        $readmemh(
            TEST_LABELS_FILE,
            expected_labels
        );

        // ---------------------------------------------------------------------
        // Display Test Configuration
        // ---------------------------------------------------------------------
        $display("");
        $display("========================================");
        $display(" FPGA OCR NEURAL NETWORK TEST");
        $display("========================================");

        $display("Test images      : %0d",NUM_TEST_IMAGES);
        $display("Pixels / image   : %0d",INPUT_SIZE);
        $display("Total pixels     : %0d",TOTAL_TEST_PIXELS);
        $display("Layer 1 mode     : binary optimized");
        $display("Layers 2-4 mode  : fixed-point MAC");
        $display("");

        // ---------------------------------------------------------------------
        // Reset DUT
        // ---------------------------------------------------------------------
        reset_dut();

        // ---------------------------------------------------------------------
        // Process All Test Images Sequentially
        // ---------------------------------------------------------------------
        //
        // The DUT still processes only one image at a time.
        //
        // For every test image:
        //
        //     1. Wait until input_ready is asserted.
        //     2. Send exactly 784 binary pixels.
        //     3. Start the inference timer.
        //     4. Wait for result_valid.
        //     5. Calculate inference latency.
        //     6. Compare predicted_digit against expected_labels[test_index].
        //     7. Wait until the DUT is ready for the next image.
        //
        for (test_index = 0;test_index < NUM_TEST_IMAGES;test_index = test_index + 1)
        begin
            $display("");
            $display("----------------------------------------");
            $display("Image %0d / %0d",test_index + 1,NUM_TEST_IMAGES);
            $display("Expected digit : %0d",expected_labels[test_index]);

            // -------------------------------------------------------------
            // Send One Complete Image
            // -------------------------------------------------------------
            $display("Sending %0d binary MNIST pixels...",INPUT_SIZE);

            send_image(test_index);

            // Start measuring neural-network inference latency only after the
            // last input pixel has entered the DUT.
            //
            // This intentionally excludes image-transfer time.
            inference_start_time = $time;

            $display("Image received by DUT.");

            // -------------------------------------------------------------
            // Wait for Sequential Neural-Network Inference
            // -------------------------------------------------------------
            $display("Waiting for neural-network inference...");
            wait_for_result();

            // -------------------------------------------------------------
            // Calculate Current-Image Latency
            // -------------------------------------------------------------
            inference_end_time = $time;

            inference_latency = inference_end_time - inference_start_time;

            inference_latency_ns = inference_latency;

            inference_latency_us = inference_latency_ns / 1000.0;

            // -------------------------------------------------------------
            // Update Latency Statistics
            // -------------------------------------------------------------

            total_inference_cycles = total_inference_cycles + inference_cycles;

            total_latency_us = total_latency_us + inference_latency_us;

            if (inference_cycles < minimum_inference_cycles)
            begin
                minimum_inference_cycles = inference_cycles;
            end

            if (inference_cycles > maximum_inference_cycles)
            begin
                maximum_inference_cycles = inference_cycles;
            end

            // -------------------------------------------------------------
            // Check Classification
            // -------------------------------------------------------------
            check_result(test_index,expected_labels[test_index]);

            // -------------------------------------------------------------
            // Wait for the DUT to Accept the Next Image
            // -------------------------------------------------------------
            //
            // After result_valid, nn_core transitions through:
            //
            //     OUTPUT_RESULT
            //         |
            //         v
            //       IDLE
            //         |
            //         v
            //     WAIT_FOR_DATA
            //
            // input_ready is asserted again only when a new image can safely
            // be written into input_buffer.
            //
            if (test_index < NUM_TEST_IMAGES - 1)
            begin
                while (!input_ready)
                    @(posedge clk);
            end

        end

        // ---------------------------------------------------------------------
        // Final Test Summary
        // ---------------------------------------------------------------------
        $display("");
        $display("========================================");
        $display(" FPGA OCR TEST SUMMARY");
        $display("========================================");

        $display("Images tested       : %0d",NUM_TEST_IMAGES);
        $display("Correct             : %0d",pass_count);
        $display("Incorrect           : %0d",fail_count);
        $display("Accuracy            : %0.2f %%",
            (
                100.0
                * pass_count
                / NUM_TEST_IMAGES
            )
        );
        $display("");
        $display("Minimum cycles      : %0d",minimum_inference_cycles);
        $display("Maximum cycles      : %0d",maximum_inference_cycles);
        $display("Average cycles      : %0.2f",
            (
                1.0
                * total_inference_cycles
                / NUM_TEST_IMAGES
            )
        );
        $display("");
        $display("Minimum latency     : %0.3f us",
            (
                minimum_inference_cycles
                * CLK_PERIOD
                / 1000.0
            )
        );
        $display("Maximum latency     : %0.3f us",
            (
                maximum_inference_cycles
                * CLK_PERIOD
                / 1000.0
            )
        );

        $display("Average latency     : %0.3f us",
            (
                total_latency_us
                / NUM_TEST_IMAGES
            )
        );
        $display("========================================");
        $display("");
        $display("Simulation completed successfully.");

        $finish;
    end

endmodule