#!/usr/bin/env python3

"""
Convert the raw hexadecimal neural-network weight files generated by
quantize.py into Intel Quartus Memory Initialization Files (MIF).

The input files contain one signed 16-bit two's-complement hexadecimal
weight per line, for example:

    003A
    FFF2
    0018
    C000

The output files use the Quartus MIF syntax:

    WIDTH = 16;
    DEPTH = <number of weights>;

    ADDRESS_RADIX = DEC;
    DATA_RADIX = HEX;

    CONTENT BEGIN
    0 : 003A;
    1 : FFF2;
    ...
    END;

These files can be used to initialize ROM/RAM blocks in the FPGA design.
"""

# =============================================================================
# Imports
# =============================================================================

from pathlib import Path


# =============================================================================
# Files and Folders
# =============================================================================

PROJECT_DIR = Path(__file__).resolve().parent.parent

MODEL_DIR = PROJECT_DIR / "model"

QUARTUS_MIF_DIR = MODEL_DIR / "quartus_mif"

MATRIX_FILES = [
    MODEL_DIR / "matrix1_raw_hex.mif",
    MODEL_DIR / "matrix2_raw_hex.mif",
    MODEL_DIR / "matrix3_raw_hex.mif",
    MODEL_DIR / "matrix4_raw_hex.mif",
]


# =============================================================================
# Quartus MIF Parameters
# =============================================================================

DATA_WIDTH = 16


# =============================================================================
# Convert Raw Weight File
# =============================================================================

def convert_to_quartus_mif(input_file, output_file):
    """
    Convert a raw hexadecimal weight file into Quartus MIF format.

    Parameters:
        input_file (Path):
            File containing one hexadecimal weight per line.

        output_file (Path):
            Quartus-compatible MIF file to generate.
    """

    # Read all non-empty weight values.
    with open(input_file, "r") as file:
        values = [
            line.strip()
            for line in file
            if line.strip()
        ]

    # The memory depth is equal to the number of quantized weights.
    depth = len(values)

    if depth == 0:
        raise ValueError(
            f"No weight values found in {input_file}"
        )

    # Create the Quartus MIF file.
    with open(output_file, "w") as file:

        # ---------------------------------------------------------------------
        # MIF Header
        # ---------------------------------------------------------------------

        file.write(f"WIDTH = {DATA_WIDTH};\n")
        file.write(f"DEPTH = {depth};\n")
        file.write("\n")

        file.write("ADDRESS_RADIX = DEC;\n")
        file.write("DATA_RADIX = HEX;\n")
        file.write("\n")

        file.write("CONTENT BEGIN\n")

        # ---------------------------------------------------------------------
        # Weight Data
        # ---------------------------------------------------------------------

        for address, value in enumerate(values):

            # Convert the hexadecimal text into an integer.
            integer_value = int(value, 16)

            # Force the value to the selected memory width.
            integer_value &= (1 << DATA_WIDTH) - 1

            # Number of hexadecimal characters required by DATA_WIDTH.
            hex_digits = DATA_WIDTH // 4

            # Format the value as fixed-width uppercase hexadecimal.
            hex_value = f"{integer_value:0{hex_digits}X}"

            # Write:
            #
            #     address : value;
            file.write(
                f"{address} : {hex_value};\n"
            )

        file.write("END;\n")

    print(f"Input file  : {input_file}")
    print(f"Output file : {output_file}")
    print(f"Width       : {DATA_WIDTH} bits")
    print(f"Depth       : {depth}")
    print()


# =============================================================================
# Main
# =============================================================================

def main():
    """
    Convert all neural-network weight matrices into Quartus MIF files.
    """

    # Create the output directory if necessary.
    QUARTUS_MIF_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    print(f"Project directory    : {PROJECT_DIR}")
    print(f"Model directory      : {MODEL_DIR}")
    print(f"Quartus MIF directory: {QUARTUS_MIF_DIR}")
    print()

    # Convert each neural-network layer.
    # Convert each neural-network layer.
    for matrix_file in MATRIX_FILES:

        if not matrix_file.exists():
            raise FileNotFoundError(
                f"Weight file not found: {matrix_file}\n"
                f"Run ./python/quantize.py first."
            )

        # Remove "_raw_hex" from the filename for the Quartus MIF output.
        output_name = matrix_file.name.replace("_raw_hex.mif", ".mif")
        output_file = QUARTUS_MIF_DIR / output_name

        print(f"Converting {matrix_file.name} -> {output_name}...")

        convert_to_quartus_mif(matrix_file, output_file)


# =============================================================================
# Program Entry Point
# =============================================================================

if __name__ == "__main__":
    main()