#!/usr/bin/env python3

"""
Usage:
    ./python/quantize.py

Quantize the floating-point neural-network weights generated by training.py.

The floating-point model is expected at:

    ./model/mnist_model.pth

The quantized model is written to:

    ./model/mnist_model_quantized.pth

Weight representation:

    Storage width     :  16 bits signed
    Fractional bits   :  14
    Scale factor      :  16384
    Quantized minimum : -16384
    Quantized maximum :  16384

The conversion is:

    quantized_weight = round(float_weight * 16384)

followed by saturation to:

    [-16384, 16384]

The floating-point equivalent can be reconstructed using:

    float_weight = quantized_weight / 16384
"""

# =============================================================================
# Imports
# =============================================================================

from pathlib import Path
import torch
import torch.nn as nn
from training import LinearLayer, NeuralNetwork, load_data, split_data

# =============================================================================
# Files and Folders
# =============================================================================

PROJECT_DIR = Path(__file__).resolve().parent.parent

MODEL_DIR = PROJECT_DIR / "model"

FLOAT_MODEL_FILE = MODEL_DIR / "mnist_model.pth"

QUANTIZED_MODEL_FILE = MODEL_DIR / "mnist_model_quantized.pth"

DATA_DIR = PROJECT_DIR / "data"

TRAIN_FILE = DATA_DIR / "train.csv"


# =============================================================================
# Fixed-Point Quantization Parameters
# =============================================================================

# Total number of bits used to store each quantized weight.
WEIGHT_BITS = 16

# Number of fractional bits.
FRACTIONAL_BITS = 14

# Fixed-point scaling factor:
#
#     2^14 = 16384
QUANTIZATION_SCALE = 1 << FRACTIONAL_BITS

# Quantized range representing approximately -1.0 to +1.0.
QUANTIZED_MIN = -16384
QUANTIZED_MAX = 16384


# =============================================================================
# Load Floating-Point Model
# =============================================================================

def load_model():
    """
    Load the trained floating-point neural network.

    Returns:
        NeuralNetwork:
            Trained floating-point model.
    """

    if not FLOAT_MODEL_FILE.exists():
        raise FileNotFoundError(
            f"Floating-point model not found: {FLOAT_MODEL_FILE}\n"
            f"Run ./python/training.py first."
        )

    model = NeuralNetwork()

    state_dict = torch.load(FLOAT_MODEL_FILE,map_location="cpu",weights_only=True)

    model.load_state_dict(state_dict)

    model.eval()

    print(f"Loaded floating-point model : {FLOAT_MODEL_FILE}")

    return model


# =============================================================================
# Quantize Tensor
# =============================================================================

def quantize_tensor(tensor):
    """
    Convert a floating-point tensor to signed fixed-point integer values.

    Conversion:

        integer = round(float_value * 2^FRACTIONAL_BITS)

    followed by saturation to QUANTIZED_MIN..QUANTIZED_MAX.

    Args:
        tensor:
            Floating-point PyTorch tensor.

    Returns:
        quantized_tensor:
            Quantized signed integer tensor.

        clipped_values:
            Number of values that required saturation.
    """

    scaled_tensor = (tensor * QUANTIZATION_SCALE)
    rounded_tensor = torch.round(scaled_tensor)

    clipped_values = ((rounded_tensor < QUANTIZED_MIN) | (rounded_tensor > QUANTIZED_MAX)).sum().item()

    quantized_tensor = torch.clamp(rounded_tensor,QUANTIZED_MIN,QUANTIZED_MAX)
    quantized_tensor = quantized_tensor.to(torch.int16)

    return (quantized_tensor,clipped_values)


# =============================================================================
# Dequantize Tensor
# =============================================================================

def dequantize_tensor(quantized_tensor):
    """
    Convert a fixed-point integer tensor back into floating point.

    This is primarily useful for comparing the quantized model with the
    original floating-point model in Python.

    Args:
        quantized_tensor:
            Signed integer tensor.

    Returns:
        torch.Tensor:
            Floating-point representation of the quantized values.
    """

    return (
        quantized_tensor.to(torch.float32)
        / QUANTIZATION_SCALE
    )


# =============================================================================
# Quantize Model
# =============================================================================

def quantize_model(model):
    """
    Quantize every weight tensor in the neural network.

    Args:
        model:
            Trained floating-point neural network.

    Returns:
        dict:
            Quantized model parameters.
    """

    quantized_state = {}

    print()
    print("Weight Quantization")
    print("-------------------")

    for name, parameter in model.state_dict().items():
        quantized_tensor, clipped_values = quantize_tensor(
            parameter
        )

        quantized_state[name] = quantized_tensor

        float_min = parameter.min().item()
        float_max = parameter.max().item()

        integer_min = quantized_tensor.min().item()
        integer_max = quantized_tensor.max().item()

        total_values = parameter.numel()

        print()
        print(f"Layer          : {name}")
        print(f"Values         : {total_values}")
        print(f"Float minimum  : {float_min:.6f}")
        print(f"Float maximum  : {float_max:.6f}")
        print(f"Integer minimum: {integer_min}")
        print(f"Integer maximum: {integer_max}")
        print(f"Clipped values : {clipped_values}")

    return quantized_state


# =============================================================================
# Display Quantized Weights
# =============================================================================

def display_quantized_weights(model):
    """
    Display the quantized weights for each linear layer.

    At this point, load_quantized_weights() has replaced the original
    floating-point weights with their quantized/dequantized equivalents.
    """

    for i, layer in enumerate(model.children()):
        if isinstance(layer, LinearLayer):
            print()
            print(f"Layer {i + 1} Weights:")
            print(layer.weight.data)
            print(f"Shape: {layer.weight.shape}")

# =============================================================================
# Export Quantized Weights
# =============================================================================

def save_weights_as_hex(quantized_state):
    """
    Export the quantized 16-bit weights as hexadecimal values.

    One file is generated for each neural-network layer:

        matrix1.mif
        matrix2.mif
        matrix3.mif
        matrix4.mif

    Each weight is stored as a 16-bit two's-complement hexadecimal value.

    Examples:

        16384  -> 4000
        8192   -> 2000
        1      -> 0001
        0      -> 0000
        -1     -> FFFF
        -8192  -> E000
        -16384 -> C000

    The weights are flattened in the same order used by PyTorch.
    """

    weight_names = [
        "layer1.weight",
        "layer2.weight",
        "layer3.weight",
        "layer4.weight",
    ]

    for idx, weight_name in enumerate(weight_names, start=1):

        # Get the corresponding quantized weight matrix.
        weight_matrix = quantized_state[weight_name]

        # Flatten the matrix into a one-dimensional sequence.
        flattened_weights = weight_matrix.flatten().cpu().numpy()

        # Generate the output file inside the model directory.
        output_file = MODEL_DIR / f"matrix{idx}_raw_hex.mif"

        # Open the corresponding file for saving the weights.
        with open(output_file, "w") as file:

            for weight in flattened_weights:

                # Convert the quantized weight directly to a Python integer.
                int_weight = int(weight)

                # Convert the signed 16-bit value to its unsigned
                # two's-complement representation.
                hex_weight = f"{int_weight & 0xFFFF:04X}"

                # Write only the hexadecimal value.
                file.write(f"{hex_weight}\n")

        print(f"Saved Layer {idx} weights : {output_file}")

# =============================================================================
# Save Quantized Model
# =============================================================================

def save_quantized_model(quantized_state):
    """
    Save the quantized network weights and fixed-point metadata.

    The metadata allows other scripts, including a future VHDL exporter, to
    determine exactly how the stored integers represent floating-point values.

    Args:
        quantized_state:
            Dictionary containing the quantized neural-network parameters.
    """

    MODEL_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    quantized_model = {
        "weight_bits": WEIGHT_BITS,
        "fractional_bits": FRACTIONAL_BITS,
        "scale": QUANTIZATION_SCALE,
        "quantized_min": QUANTIZED_MIN,
        "quantized_max": QUANTIZED_MAX,
        "state_dict": quantized_state,
    }

    torch.save(
        quantized_model,
        QUANTIZED_MODEL_FILE,
    )

    print()
    print(f"Saved quantized model : {QUANTIZED_MODEL_FILE}")


# =============================================================================
# Display Quantization Parameters
# =============================================================================

def display_quantization_parameters():
    """
    Display the fixed-point representation used for the FPGA weights.
    """

    resolution = (
        1.0
        / QUANTIZATION_SCALE
    )

    minimum_value = (
        QUANTIZED_MIN
        / QUANTIZATION_SCALE
    )

    maximum_value = (
        QUANTIZED_MAX
        / QUANTIZATION_SCALE
    )

    print("Fixed-Point Weight Representation")
    print("---------------------------------")
    print(f"Storage width     : {WEIGHT_BITS} bits")
    print(f"Fractional bits   : {FRACTIONAL_BITS}")
    print(f"Scale factor      : {QUANTIZATION_SCALE}")
    print(f"Integer range     : {QUANTIZED_MIN} to {QUANTIZED_MAX}")
    print(f"Real-value range  : {minimum_value:.6f} to {maximum_value:.6f}")
    print(f"Resolution        : {resolution:.6f}")


# =============================================================================
# Verify Quantization
# =============================================================================

def verify_quantization(model,quantized_state):
    """
    Compare the original floating-point weights against their fixed-point
    approximations.

    Args:
        model:
            Original floating-point model.

        quantized_state:
            Quantized integer weights.
    """

    print()
    print("Quantization Error")
    print("------------------")

    for name, parameter in model.state_dict().items():
        dequantized = dequantize_tensor(
            quantized_state[name]
        )

        error = (
            parameter
            - dequantized
        )

        mean_absolute_error = (
            torch.mean(
                torch.abs(error)
            ).item()
        )

        maximum_absolute_error = (
            torch.max(
                torch.abs(error)
            ).item()
        )

        print()
        print(f"Layer             : {name}")
        print(f"Mean absolute error: {mean_absolute_error:.8f}")
        print(f"Max absolute error : {maximum_absolute_error:.8f}")


# =============================================================================
# Test Quantized Model
# =============================================================================

def load_quantized_weights(model, quantized_state):
    """
    Load quantized weights into the PyTorch model after converting them
    back to their floating-point equivalents.

    The resulting values are restricted to exactly the values representable
    by the 16-bit fixed-point format.
    """

    dequantized_state = {}

    for name, quantized_tensor in quantized_state.items():
        dequantized_state[name] = dequantize_tensor(quantized_tensor)

    model.load_state_dict(dequantized_state)

    return model


def test_model(model, X_test, y_test):
    """
    Evaluate the model using the quantized/dequantized weights.
    """

    model.eval()
    criterion = nn.CrossEntropyLoss()

    with torch.no_grad():
        outputs = model(X_test)
        loss = criterion(outputs, y_test)

        _, predicted = torch.max(outputs.data, 1)
        correct = (predicted == y_test).sum().item()
        accuracy = correct / y_test.size(0)

    print()
    print("Quantized Model Test")
    print("--------------------")
    print(f"Test Loss     : {loss.item():.4f}")
    print(f"Test Accuracy : {accuracy:.4f}")


# =============================================================================
# Main
# =============================================================================

def main():
    """
    Execute the floating-point to fixed-point model conversion.
    """

    print(f"Project directory       : {PROJECT_DIR}")
    print(f"Floating-point model    : {FLOAT_MODEL_FILE}")
    print(f"Quantized model         : {QUANTIZED_MODEL_FILE}")

    print()

    # Display the fixed-point representation used for quantization.
    display_quantization_parameters()

    # Load the trained floating-point neural network.
    model = load_model()

    # Quantize all floating-point weights to signed 16-bit integers.
    quantized_state = quantize_model(model)

    # Measure the numerical error introduced by quantization.
    verify_quantization(model, quantized_state)

    # Load the same dataset used during training.
    X, y = load_data(TRAIN_FILE)

    # Recreate the training and test datasets.
    X_train, X_test, y_train, y_test = split_data(X, y, train_ratio=0.8)

    # Replace the floating-point weights with their quantized/dequantized
    # equivalents for PyTorch inference.
    model = load_quantized_weights(model, quantized_state)

    # Display the quantized/dequantized weights for each network layer.
    display_quantized_weights(model)

    # Export the actual 16-bit integer weights for the FPGA implementation.
    save_weights_as_hex(quantized_state)

    # Evaluate the model using the quantized/dequantized weights.
    test_model(model, X_test, y_test)

    # Save the integer weights and fixed-point metadata.
    save_quantized_model(quantized_state)


# =============================================================================
# Program Entry Point
# =============================================================================

if __name__ == "__main__":
    main()