#!/usr/bin/env python3

"""
Test and visualize the neural network using the quantized weights.

The script loads the signed 16-bit weights generated by quantize.py and
converts them back to their fixed-point-equivalent floating-point values
for inference with PyTorch.

For the current Q1.14-style representation:

    weight_bits     = 16
    fractional_bits = 14
    scale           = 16384

Example:

    quantized weight = 8192

    PyTorch value:

        8192 / 16384 = 0.5

The resulting PyTorch model therefore uses the same quantized weight
values that will later be represented in the FPGA implementation.
"""

# =============================================================================
# Imports
# =============================================================================

from pathlib import Path

import matplotlib
# If necessary, install TkAgg (sudo apt install python3-tk)
matplotlib.use("TkAgg")

import matplotlib.pyplot as plt
import torch

from training import NeuralNetwork, load_data, split_data


# =============================================================================
# Files and Folders
# =============================================================================

PROJECT_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_DIR / "data"
TRAIN_FILE = DATA_DIR / "train.csv"

MODEL_DIR = PROJECT_DIR / "model"
QUANTIZED_MODEL_FILE = MODEL_DIR / "mnist_model_quantized.pth"


# =============================================================================
# Load Quantized Model
# =============================================================================

def load_quantized_model():
    """
    Load the signed 16-bit quantized weights and reconstruct the PyTorch model.

    The saved integer weights cannot be used directly by the floating-point
    PyTorch network. Each weight is therefore divided by the saved scale
    factor before being loaded into the model.

    Returns:
        NeuralNetwork:
            Model containing the quantized/dequantized weights.
    """

    # Verify that quantize.py has already generated the quantized model.
    if not QUANTIZED_MODEL_FILE.exists():
        raise FileNotFoundError(
            f"Quantized model not found: {QUANTIZED_MODEL_FILE}\n"
            f"Run ./python/quantize.py first."
        )

    # Load the quantized weights and their fixed-point metadata.
    quantized_model = torch.load(
        QUANTIZED_MODEL_FILE,
        map_location="cpu",
        weights_only=True,
    )

    # Extract the signed integer weight tensors.
    quantized_state = quantized_model["state_dict"]

    # Extract the fixed-point scale factor.
    scale = quantized_model["scale"]

    # Create a new instance of the same network used during training.
    model = NeuralNetwork()

    # Dictionary used to hold the fixed-point-equivalent floating-point weights.
    dequantized_state = {}

    # Convert each signed integer weight back to its represented real value.
    for name, quantized_tensor in quantized_state.items():
        dequantized_state[name] = quantized_tensor.to(torch.float32) / scale

    # Load the quantized/dequantized weights into the PyTorch network.
    model.load_state_dict(dequantized_state)

    # Set the network to inference mode.
    model.eval()

    print(f"Loaded quantized model : {QUANTIZED_MODEL_FILE}")
    print(f"Weight bits            : {quantized_model['weight_bits']}")
    print(f"Fractional bits        : {quantized_model['fractional_bits']}")
    print(f"Scale factor           : {scale}")
    print(f"Quantized minimum      : {quantized_model['quantized_min']}")
    print(f"Quantized maximum      : {quantized_model['quantized_max']}")

    return model


# =============================================================================
# Visualize Digit
# =============================================================================

def visualize_digit(tensor, actual_label=None, predicted_label=None):
    """
    Visualize a digit represented by a flattened 784-element array.

    Parameters:
        tensor (numpy.ndarray):
            A flattened NumPy array representing the 28 x 28 digit.

        actual_label (int):
            Expected MNIST classification.

        predicted_label (int):
            Classification predicted by the quantized model.
    """

    # Reshape the flattened tensor into the original 28 x 28 MNIST image.
    digit_image = tensor.reshape(28, 28)

    # Create a new figure.
    plt.figure(figsize=(5, 5))

    # Display the digit using a grayscale color map.
    plt.imshow(digit_image, cmap="gray")

    # Display the classification result above the image.
    if actual_label is not None and predicted_label is not None:
        plt.title(f"Actual: {actual_label}    Predicted: {predicted_label}")

    # Remove the plot axes.
    plt.axis("off")

    # Adjust the layout.
    plt.tight_layout()

    # Display the image in an interactive window.
    plt.show()


# =============================================================================
# Test and Visualize
# =============================================================================

def test_and_visualize(model, X_test, y_test, index):
    """
    Test the quantized model on one sample and visualize the digit image.

    Parameters:
        model (NeuralNetwork):
            Model containing the quantized/dequantized weights.

        X_test (torch.Tensor):
            Test-set features.

        y_test (torch.Tensor):
            Test-set labels.

        index (int):
            Index of the sample to visualize and predict.
    """

    # Verify that the requested index exists in the test dataset.
    if index < 0 or index >= X_test.size(0):
        raise IndexError(
            f"Index {index} is outside the valid range "
            f"0 to {X_test.size(0) - 1}."
        )

    # Set the model to evaluation mode.
    model.eval()

    # Extract the sample at the specified index.
    #
    # Original shape:
    #
    #     (784,)
    #
    # Shape after unsqueeze:
    #
    #     (1, 784)
    sample = X_test[index].unsqueeze(0)

    # Get the expected classification.
    label = y_test[index].item()

    # Run inference without calculating gradients.
    with torch.no_grad():

        # Calculate the ten output logits.
        output = model(sample)

        # Find the output neuron containing the largest logit.
        _, predicted = torch.max(output.data, 1)

        # Convert the predicted class to a Python integer.
        predicted_label = predicted.item()

    # Print the raw output logits from the quantized model.
    print()
    print("Output logits:")
    print(output)

    # Print the actual and predicted labels.
    print()
    print(f"Actual Label    : {label}")
    print(f"Predicted Label : {predicted_label}")

    # Print whether the classification was correct.
    print(f"Classification  : {'CORRECT' if label == predicted_label else 'INCORRECT'}")

    # Visualize the selected digit.
    visualize_digit(sample.cpu().numpy().flatten(), actual_label=label, predicted_label=predicted_label)


# =============================================================================
# Main
# =============================================================================

def main():
    """
    Load the quantized model and test one sample from the test dataset.
    """

    print(f"Project directory : {PROJECT_DIR}")
    print(f"Training file     : {TRAIN_FILE}")
    print(f"Quantized model   : {QUANTIZED_MODEL_FILE}")

    # Load the neural network using the quantized weights.
    model = load_quantized_model()

    # Load the same preprocessed dataset used during training.
    X, y = load_data(TRAIN_FILE)

    # Recreate the training and test datasets.
    _, X_test, _, y_test = split_data(X, y, train_ratio=0.8)

    # Select the test sample to classify and visualize.
    idx = 5

    print()
    print(f"Number of test samples : {X_test.size(0)}")
    print(f"Selected sample        : {idx}")

    # Test the selected sample using the quantized weights.
    test_and_visualize(model,X_test,y_test,index=idx)


# =============================================================================
# Program Entry Point
# =============================================================================

if __name__ == "__main__":
    main()