#!/usr/bin/env python3

"""
Test and visualize the neural network using the exact weights exported for FPGA.

Unlike the previous version, this script does not load the weights from
mnist_model_quantized.pth. Instead, it reads the same Intel Quartus MIF files
used to initialize the FPGA weight ROMs:

    model/quartus_mif/matrix1.mif
    model/quartus_mif/matrix2.mif
    model/quartus_mif/matrix3.mif
    model/quartus_mif/matrix4.mif

The MIF values are signed 16-bit Q1.14-style weights:

    weight_bits     = 16
    fractional_bits = 14
    scale           = 16384

Two inference checks are performed with the same FPGA weights:

1. PyTorch inference using the MIF weights dequantized back to floating point.
2. Integer fixed-point inference that mirrors the current VHDL dense-layer
   datapath:

       accumulate -> arithmetic shift right by 14 -> 16-bit saturation -> ReLU

   ReLU is applied after Layers 1, 2, and 3, but not after Layer 4.

The input sample is also read from the same files used by nn_core_tb.v:

    data/input_image.mem
    data/expected_class.txt

This makes the Python and Questa tests use the same input pixels, expected
label, and neural-network weight values.
"""

# =============================================================================
# Imports
# =============================================================================

from pathlib import Path
import re

import matplotlib
# If necessary, install TkAgg (sudo apt install python3-tk)
matplotlib.use("TkAgg")

import matplotlib.pyplot as plt
import numpy as np
import torch

from training import NeuralNetwork


# =============================================================================
# Files and Folders
# =============================================================================

PROJECT_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_DIR / "data"
INPUT_IMAGE_FILE = DATA_DIR / "input_image.mem"
EXPECTED_CLASS_FILE = DATA_DIR / "expected_class.txt"

MODEL_DIR = PROJECT_DIR / "model"
QUARTUS_MIF_DIR = MODEL_DIR / "quartus_mif"

MATRIX_FILES = [
    QUARTUS_MIF_DIR / "matrix1.mif",
    QUARTUS_MIF_DIR / "matrix2.mif",
    QUARTUS_MIF_DIR / "matrix3.mif",
    QUARTUS_MIF_DIR / "matrix4.mif",
]


# =============================================================================
# Neural-Network and Fixed-Point Configuration
# =============================================================================

INPUT_SIZE = 784

LAYER_SHAPES = [
    (784, 64),
    (64, 64),
    (64, 32),
    (32, 10),
]

WEIGHT_BITS = 16
FRACTIONAL_BITS = 14
QUANTIZATION_SCALE = 1 << FRACTIONAL_BITS

DATA_BITS = 16
DATA_MIN = -(1 << (DATA_BITS - 1))
DATA_MAX = (1 << (DATA_BITS - 1)) - 1

# Print Layer 1, Layer 2, Layer 3, and Layer 4 values so they can be compared
# directly with the corresponding buffers/signals in Questa.
PRINT_INTERMEDIATE_VALUES = True


# =============================================================================
# Read Quartus MIF
# =============================================================================

def read_quartus_mif(filepath):
    """
    Read one Intel Quartus Memory Initialization File.

    The files generated by convert_to_quartus.py use this format:

        WIDTH = 16;
        DEPTH = 50176;

        ADDRESS_RADIX = DEC;
        DATA_RADIX = HEX;

        CONTENT BEGIN
        0 : 0BAD;
        1 : EF8B;
        ...
        END;

    The hexadecimal values are converted from their unsigned text
    representation into signed two's-complement integers.

    Parameters:
        filepath (Path):
            Quartus MIF file to read.

    Returns:
        numpy.ndarray:
            One-dimensional signed integer array in FPGA ROM address order.
    """

    if not filepath.exists():
        raise FileNotFoundError(
            f"Quartus MIF not found: {filepath}\n"
            f"Run ./python/quantize.py and ./python/convert_to_quartus.py first."
        )

    text = filepath.read_text()

    width_match = re.search(r"\bWIDTH\s*=\s*(\d+)\s*;", text, re.IGNORECASE)
    depth_match = re.search(r"\bDEPTH\s*=\s*(\d+)\s*;", text, re.IGNORECASE)

    if width_match is None or depth_match is None:
        raise ValueError(f"Invalid Quartus MIF header: {filepath}")

    width = int(width_match.group(1))
    depth = int(depth_match.group(1))

    if width != WEIGHT_BITS:
        raise ValueError(
            f"Unexpected weight width in {filepath}: "
            f"expected {WEIGHT_BITS}, found {width}."
        )

    values = np.zeros(depth, dtype=np.int64)
    addresses_seen = set()

    entry_pattern = re.compile(
        r"^\s*(\d+)\s*:\s*([0-9A-Fa-f]+)\s*;\s*$",
        re.MULTILINE,
    )

    sign_bit = 1 << (width - 1)
    modulus = 1 << width

    for match in entry_pattern.finditer(text):
        address = int(match.group(1))
        unsigned_value = int(match.group(2), 16)

        if address < 0 or address >= depth:
            raise ValueError(
                f"Address {address} is outside MIF depth {depth}: {filepath}"
            )

        # Interpret the WIDTH-bit hexadecimal word as signed two's complement.
        if unsigned_value & sign_bit:
            signed_value = unsigned_value - modulus
        else:
            signed_value = unsigned_value

        values[address] = signed_value
        addresses_seen.add(address)

    if len(addresses_seen) != depth:
        raise ValueError(
            f"MIF {filepath} declares DEPTH={depth}, but only "
            f"{len(addresses_seen)} explicit values were found."
        )

    return values


# =============================================================================
# Load FPGA Weights
# =============================================================================

def load_fpga_weights():
    """
    Load all four neural-network matrices directly from the Quartus MIF files.

    The matrix shape and flattening order match the FPGA ROM address equation:

        address = input_index * output_count + output_index

    quantize.py flattens each PyTorch matrix in row-major order, and
    convert_to_quartus.py preserves that ordering when creating the MIF.

    Returns:
        list[numpy.ndarray]:
            Four signed integer matrices with shapes:

                784 x 64
                 64 x 64
                 64 x 32
                 32 x 10
    """

    matrices = []

    for layer_index, (filepath, shape) in enumerate(
        zip(MATRIX_FILES, LAYER_SHAPES),
        start=1,
    ):
        flattened_weights = read_quartus_mif(filepath)
        expected_depth = shape[0] * shape[1]

        if flattened_weights.size != expected_depth:
            raise ValueError(
                f"Layer {layer_index} weight count mismatch: "
                f"expected {expected_depth}, found {flattened_weights.size}."
            )

        weight_matrix = flattened_weights.reshape(shape)
        matrices.append(weight_matrix)

        print(f"Loaded FPGA Layer {layer_index} : {filepath}")
        print(f"Shape                       : {weight_matrix.shape}")
        print(f"Integer minimum             : {weight_matrix.min()}")
        print(f"Integer maximum             : {weight_matrix.max()}")

    print(f"Weight bits                  : {WEIGHT_BITS}")
    print(f"Fractional bits              : {FRACTIONAL_BITS}")
    print(f"Scale factor                 : {QUANTIZATION_SCALE}")

    return matrices


# =============================================================================
# Build PyTorch Model from FPGA Weights
# =============================================================================

def build_model_from_fpga_weights(weight_matrices):
    """
    Reconstruct the PyTorch network using the exact integer weights stored in
    the Quartus MIF files.

    PyTorch performs floating-point arithmetic, so the FPGA integer weight is
    divided by 2^14 before it is copied into the corresponding layer.

    This path verifies the represented quantized model, while
    run_fixed_point_inference() below mirrors the integer RTL datapath.
    """

    model = NeuralNetwork()

    layer_names = [
        "layer1.weight",
        "layer2.weight",
        "layer3.weight",
        "layer4.weight",
    ]

    fpga_state = {}

    for layer_name, integer_weights in zip(layer_names, weight_matrices):
        fpga_state[layer_name] = torch.from_numpy(
            integer_weights.astype(np.float32) / QUANTIZATION_SCALE
        )

    model.load_state_dict(fpga_state)
    model.eval()

    return model


# =============================================================================
# Load the Same Input Used by the Verilog Testbench
# =============================================================================

def load_testbench_sample():
    """
    Load the same binary image and expected digit consumed by nn_core_tb.v.

    input_image.mem must contain exactly 784 lines containing only 0 or 1.
    expected_class.txt must contain one decimal MNIST class from 0 through 9.
    """

    if not INPUT_IMAGE_FILE.exists():
        raise FileNotFoundError(
            f"FPGA test image not found: {INPUT_IMAGE_FILE}"
        )

    if not EXPECTED_CLASS_FILE.exists():
        raise FileNotFoundError(
            f"FPGA expected-class file not found: {EXPECTED_CLASS_FILE}"
        )

    pixels = [
        int(line.strip())
        for line in INPUT_IMAGE_FILE.read_text().splitlines()
        if line.strip()
    ]

    if len(pixels) != INPUT_SIZE:
        raise ValueError(
            f"Expected {INPUT_SIZE} pixels in {INPUT_IMAGE_FILE}, "
            f"found {len(pixels)}."
        )

    if any(pixel not in (0, 1) for pixel in pixels):
        raise ValueError(
            f"{INPUT_IMAGE_FILE} must contain only binary values 0 and 1."
        )

    expected_label = int(EXPECTED_CLASS_FILE.read_text().strip())

    if expected_label < 0 or expected_label > 9:
        raise ValueError(
            f"Expected class must be in the range 0..9, found {expected_label}."
        )

    sample = np.asarray(pixels, dtype=np.int64)

    return sample, expected_label


# =============================================================================
# Fixed-Point Helpers
# =============================================================================

def saturate_to_data_width(values):
    """Saturate values to the signed DATA_BITS range used by data_t in VHDL."""

    return np.clip(values, DATA_MIN, DATA_MAX).astype(np.int64)


def run_dense_layer_fixed_point(input_values, weight_matrix, apply_relu):
    """
    Execute one layer using the arithmetic currently implemented by
    dense_layer.vhd.

    Operation for every neuron:

        accumulator = sum(input[i] * weight[i][neuron])
        activation  = accumulator >> FRACTIONAL_BITS
        activation  = saturate_to_16_bits(activation)

        if apply_relu:
            activation = max(activation, 0)

    NumPy int64 is used as the software accumulator. The current VHDL uses a
    signed 48-bit accumulator; the expected network values fit comfortably in
    int64 for this reference calculation.
    """

    input_values = np.asarray(input_values, dtype=np.int64)
    weight_matrix = np.asarray(weight_matrix, dtype=np.int64)

    accumulators = input_values @ weight_matrix

    # np.right_shift performs an arithmetic right shift for signed integers,
    # matching ieee.numeric_std.shift_right() on a signed VHDL value.
    activations = np.right_shift(accumulators, FRACTIONAL_BITS)
    activations = saturate_to_data_width(activations)

    if apply_relu:
        activations = np.maximum(activations, 0)

    return activations.astype(np.int64)


# =============================================================================
# FPGA-Equivalent Fixed-Point Inference
# =============================================================================

def run_fixed_point_inference(sample, weight_matrices):
    """
    Run the complete network using the same integer weight matrices and current
    fixed-point layer operations as the VHDL implementation.

    Layer 1 receives binary 0/1 pixels. The VHDL binary-input optimization
    replaces multiplication by either zero or the weight itself, which is
    mathematically identical to the matrix multiplication performed here.
    """

    layer1 = run_dense_layer_fixed_point(
        sample,
        weight_matrices[0],
        apply_relu=True,
    )

    layer2 = run_dense_layer_fixed_point(
        layer1,
        weight_matrices[1],
        apply_relu=True,
    )

    layer3 = run_dense_layer_fixed_point(
        layer2,
        weight_matrices[2],
        apply_relu=True,
    )

    layer4 = run_dense_layer_fixed_point(
        layer3,
        weight_matrices[3],
        apply_relu=False,
    )

    predicted_label = int(np.argmax(layer4))

    return layer1, layer2, layer3, layer4, predicted_label


# =============================================================================
# Visualize Digit
# =============================================================================

def visualize_digit(tensor, actual_label=None, predicted_label=None):
    """
    Visualize a digit represented by a flattened 784-element array.

    Parameters:
        tensor (numpy.ndarray):
            A flattened NumPy array representing the 28 x 28 digit.

        actual_label (int):
            Expected MNIST classification.

        predicted_label (int):
            Classification predicted using the FPGA MIF weights.
    """

    # Reshape the flattened tensor into the original 28 x 28 MNIST image.
    digit_image = tensor.reshape(28, 28)

    # Create a new figure.
    plt.figure(figsize=(5, 5))

    # Display the already-binarized image used by the FPGA testbench.
    plt.imshow(digit_image, cmap="gray", vmin=0, vmax=1)

    # Display the classification result above the image.
    if actual_label is not None and predicted_label is not None:
        plt.title(f"Actual: {actual_label}    Predicted: {predicted_label}")

    # Remove the plot axes.
    plt.axis("off")

    # Adjust the layout.
    plt.tight_layout()

    # Display the image in an interactive window.
    plt.show()


# =============================================================================
# Test and Visualize
# =============================================================================

def test_and_visualize(model, weight_matrices, sample, label):
    """
    Test one FPGA test vector using the exact Quartus MIF weights and visualize
    the same binary digit sent to nn_core_tb.v.

    Both the dequantized PyTorch model and the integer fixed-point reference are
    evaluated so differences between model quantization and RTL arithmetic can
    be identified separately.
    """

    # Convert the FPGA binary sample to the floating-point tensor required by
    # the PyTorch model reconstructed from the MIF weights.
    pytorch_sample = torch.from_numpy(
        sample.astype(np.float32)
    ).unsqueeze(0)

    # -------------------------------------------------------------------------
    # PyTorch inference with the exact MIF weights
    # -------------------------------------------------------------------------

    model.eval()

    with torch.no_grad():
        pytorch_output = model(pytorch_sample)
        pytorch_predicted = int(torch.argmax(pytorch_output, dim=1).item())

    # -------------------------------------------------------------------------
    # FPGA-equivalent fixed-point inference
    # -------------------------------------------------------------------------

    layer1, layer2, layer3, layer4, fpga_predicted = run_fixed_point_inference(
        sample,
        weight_matrices,
    )

    print()
    print("PyTorch logits using exact FPGA MIF weights:")
    print(pytorch_output)

    if PRINT_INTERMEDIATE_VALUES:
        print()
        print("Fixed-point Layer 1 outputs (64):")
        print(layer1)
        print()
        print("Fixed-point Layer 2 outputs (64):")
        print(layer2)
        print()
        print("Fixed-point Layer 3 outputs (32):")
        print(layer3)

    print()
    print("Fixed-point Layer 4 logits (10):")
    print(layer4)

    print()
    print(f"Actual Label                  : {label}")
    print(f"PyTorch/MIF Predicted Label   : {pytorch_predicted}")
    print(f"FPGA Fixed-Point Prediction   : {fpga_predicted}")
    print(f"FPGA Fixed-Point Classification: {'CORRECT' if label == fpga_predicted else 'INCORRECT'}")

    # Visualize exactly the binary image used by the Verilog testbench.
    visualize_digit(
        sample,
        actual_label=label,
        predicted_label=fpga_predicted,
    )


# =============================================================================
# Main
# =============================================================================

def main():
    """
    Load the exact Quartus FPGA weights and the same test vector used by Questa,
    then run both PyTorch and fixed-point reference inference.
    """

    print(f"Project directory   : {PROJECT_DIR}")
    print(f"FPGA input image    : {INPUT_IMAGE_FILE}")
    print(f"FPGA expected class : {EXPECTED_CLASS_FILE}")
    print(f"Quartus MIF folder  : {QUARTUS_MIF_DIR}")
    print()

    # Load the exact signed integer weights used by the FPGA ROMs.
    weight_matrices = load_fpga_weights()

    # Reconstruct a PyTorch model directly from those same MIF values.
    model = build_model_from_fpga_weights(weight_matrices)

    # Load exactly the same image and label used by nn_core_tb.v.
    sample, label = load_testbench_sample()

    print()
    print(f"Input pixels        : {sample.size}")
    print(f"Expected label      : {label}")

    # Test the FPGA reference data and display the digit.
    test_and_visualize(
        model,
        weight_matrices,
        sample,
        label,
    )


# =============================================================================
# Program Entry Point
# =============================================================================

if __name__ == "__main__":
    main()