library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.nn_config_pkg.all;
use work.nn_types_pkg.all;

-- =============================================================================
-- ArgMax
-- =============================================================================
--
-- Finds the index of the largest value produced by the final neural-network
-- layer.
--
-- The ArgMax unit compares one output per clock cycle.
--
-- The index containing the largest value becomes the predicted output.
--
-- =============================================================================

entity argmax is
    port (
        -- clock and Reset
        clk : in std_logic;
        rst : in std_logic;
        -- Start one ArgMax operation
        start : in std_logic;
        -- Ten output values generated by Layer 4
        values : in data_array_t(0 to NUM_CLASSES - 1);
        -- Pulses high for one clock when the result is available
        done : out std_logic;
        -- MNIST digit from 0 to 9
        class_out : out unsigned(3 downto 0)
    );
end entity argmax;


architecture rtl of argmax is

    -- Current output being examined
    signal index : natural range 0 to NUM_CLASSES - 1 := 0;
    -- Largest value seen so far
    signal maximum_value : data_t := (others => '0');
    -- Index corresponding to maximum_value
    signal maximum_index : natural range 0 to NUM_CLASSES - 1 := 0;
    -- Indicates that an ArgMax operation is currently running
    signal running : std_logic := '0';

begin

    process(clk)
    begin

        if rising_edge(clk) then

            if rst = '1' then
                index         <= 0;
                maximum_value <= (others => '0');
                maximum_index <= 0;
                running <= '0';
                done    <= '0';
                class_out <= (others => '0');
            else
                -- done is a one-clock pulse
                done <= '0';

                -- ----------------------------------------------------------------
                -- Start ArgMax
                -- ----------------------------------------------------------------
                if start = '1' and running = '0' then
                    -- Use output zero as the initial maximum
                    maximum_value <= values(0);
                    maximum_index <= 0;
                    -- Start comparisons from output one
                    index <= 1;
                    running <= '1';

                -- ----------------------------------------------------------------
                -- Compare remaining outputs
                -- ----------------------------------------------------------------
                elsif running = '1' then
                    -- The final comparison needs special handling because VHDL
                    -- signal assignments do not take effect until the process
                    -- suspends.
                    if index = NUM_CLASSES - 1 then
                        if values(index) > maximum_value then
                            class_out <= to_unsigned(index,class_out'length);
                        else
                            class_out <= to_unsigned(maximum_index,class_out'length);
                        end if;
                        done    <= '1';
                        running <= '0';
                    else
                        -- Update the currently known maximum
                        if values(index) > maximum_value then
                            maximum_value <= values(index);
                            maximum_index <= index;
                        end if;
                        index <= index + 1;
                    end if;
                end if;

            end if;

        end if;

    end process;

end architecture rtl;