library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.nn_config_pkg.all;
use work.nn_types_pkg.all;

-- =============================================================================
-- ArgMax
-- =============================================================================
--
-- Finds the index of the largest value produced by the final neural-network
-- layer.
--
-- The ArgMax unit compares one output per clock cycle.
--
-- The index containing the largest value becomes the predicted output.
--
-- =============================================================================

entity argmax is
    port (
        -- clock and Reset
        clk : in std_logic;
        rst : in std_logic;
        -- Start one ArgMax operation
        start : in std_logic;
        -- Ten output values generated by Layer 4
        values : in logit_array_t(0 to NUM_CLASSES - 1);
        -- Pulses high for one clock when the result is available
        done : out std_logic;
        -- MNIST digit from 0 to 9
        class_out : out unsigned(3 downto 0)
    );
end entity argmax;


architecture rtl of argmax is

    -- Current output index being evaluated.
    signal index : natural range 0 to NUM_CLASSES - 1 := 0;
    -- Largest value found so far.
    signal max_value : logit_t := (others => '0');
    -- Index corresponding to max_value.
    signal max_index : natural range 0 to NUM_CLASSES - 1 := 0;
    -- Internal done signal.
    signal done_i : std_logic := '0';
    -- Indicates whether an ArgMax operation is active.
    signal busy_i : std_logic := '0';

begin

    -- Drive output ports.
    done <= done_i;

    class_out <= to_unsigned(max_index,class_out'length);

    -- =========================================================================
    -- Sequential ArgMax
    -- =========================================================================
    --
    -- The first Layer-4 value is used as the initial maximum.
    --
    -- This is essential because neural-network logits may be negative.
    --
    -- Initializing max_value to zero would incorrectly return class 0 whenever
    -- all ten logits are negative.
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                index <= 0;
                max_value <= (others => '0');
                max_index <= 0;
                done_i <= '0';
                busy_i <= '0';
            else
                -- done is a one-clock pulse.
                done_i <= '0';
                if busy_i = '0' then
                    if start = '1' then
                        -- Initialize the comparison using class 0 itself,
                        -- rather than using numeric zero.
                        max_value <= values(0);
                        max_index <= 0;
                        -- Start comparing from class 1.
                        index <= 1;
                        busy_i <= '1';
                    end if;
                else
                    -- Compare the current logit against the largest value found
                    -- so far.
                    if values(index) > max_value then
                        max_value <= values(index);
                        max_index <= index;
                    end if;
                    -- After class 9 has been evaluated, publish the result.
                    if index = NUM_CLASSES - 1 then
                        done_i <= '1';
                        busy_i <= '0';
                    else
                        index <= index + 1;
                    end if;
                end if;
            end if;
        end if;

    end process;

end architecture rtl;