library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.nn_config_pkg.all;
use work.nn_types_pkg.all;
use work.nn_weight_init_pkg.all;

-- =============================================================================
-- Neural-Network Core
-- =============================================================================
--
-- Top-level controller for the parallel-output MNIST neural-network
-- implementation.
--
-- Only ONE image is processed at a time.
--
-- A new image is accepted only after the previous image has completed all
-- neural-network layers and the classification result has been generated.
--
-- Network topology:
--
--     784 binary input pixels
--              |
--              v
--       Layer 1: 784 -> 64
--              |
--             ReLU
--              |
--              v
--       Layer 2: 64 -> 64
--              |
--             ReLU
--              |
--              v
--       Layer 3: 64 -> 32
--              |
--             ReLU
--              |
--              v
--       Layer 4: 32 -> 10
--              |
--              v
--            ArgMax
--              |
--              v
--       predicted_digit
--
-- Layer 1 Optimization:
--
-- The input_buffer stores each MNIST pixel using only one bit because
-- training.py already binarizes the original grayscale pixels:
--
--     pixel <= 127 -> 0
--     pixel >  127 -> 1
--
-- Therefore the dense-layer engine can bypass the multiplier for Layer 1:
--
--     input = 0 -> contribution = 0
--     input = 1 -> contribution = weight
--
-- The dense_binary_input_mode signal enables this optimization only while
-- Layer 1 is active.
--
-- Top-level Finite State Machine (sequential)
--
--     IDLE
--       |
--       v
--     WAIT_FOR_DATA
--       |
--       | 784 pixels received
--       v
--     LAYER1
--       |
--       v
--     LAYER2
--       |
--       v
--     LAYER3
--       |
--       v
--     LAYER4
--       |
--       v
--     ARGMAX_STATE
--       |
--       v
--     OUTPUT_RESULT
--       |
--       v
--     IDLE
--
-- =============================================================================

entity nn_core is
    port (
        -- Clock and reset signals
        clk : in std_logic;
        rst : in std_logic;
        -- ---------------------------------------------------------------------
        -- Input Pixel Stream
        -- ---------------------------------------------------------------------
        --
        -- pixel_in contains one already-binarized MNIST pixel:
        --
        --     '0' -> original grayscale pixel <= 127
        --     '1' -> original grayscale pixel > 127
        --
        -- pixel_valid must be asserted when pixel_in contains a valid pixel
        pixel_in    : in std_logic;
        pixel_valid : in std_logic;
        -- High while the core can accept pixels for a new image
        input_ready : out std_logic;
        -- ---------------------------------------------------------------------
        -- Classification Output
        -- ---------------------------------------------------------------------
        -- Pulses high when predicted_digit contains a valid classification
        result_valid : out std_logic;
        -- Predicted MNIST digit from 0 to 9
        predicted_digit : out unsigned(3 downto 0)
    );
end entity nn_core;

architecture rtl of nn_core is

    -- =============================================================================
    -- Top-Level State Machine
    -- =============================================================================
    type state_t is (
        IDLE,
        WAIT_FOR_DATA,
        LAYER1,
        LAYER2,
        LAYER3,
        LAYER4,
        START_ARGMAX,
        ARGMAX_STATE,
        OUTPUT_RESULT);
    signal state : state_t := IDLE;

    -- =============================================================================
    -- Input Buffer
    -- =============================================================================
    -- Clears the previously stored image before receiving a new one.
    signal input_buffer_clear : std_logic := '0';
    -- Asserted by input_buffer after all 784 pixels are stored.
    signal image_ready : std_logic;
    -- Address generated by the dense-layer engine when reading Layer 1 inputs.
    signal input_buffer_address : natural range 0 to INPUT_SIZE - 1 := 0;
    -- input_buffer converts the selected one-bit pixel to data_t:
    --
    --     0 -> signed 0
    --     1 -> signed 1
    signal input_buffer_data : data_t;

    -- =============================================================================
    -- Intermediate Activation Buffers
    -- =============================================================================
    --
    -- Layer 1 through Layer 3 outputs are stored as signed fixed-point `data_t`
    -- values
    -- Layer 4 contains the ten output logits used by ArgMax.
    signal layer1_buffer : data_array_t(0 to LAYER1_OUTPUTS - 1) := (others => (others => '0'));
    signal layer2_buffer : data_array_t(0 to LAYER2_OUTPUTS - 1) := (others => (others => '0'));
    signal layer3_buffer : data_array_t(0 to LAYER3_OUTPUTS - 1) := (others => (others => '0'));
    signal layer4_buffer : logit_array_t(0 to LAYER4_OUTPUTS - 1) := (others => (others => '0'));

    -- =============================================================================
    -- Shared Dense-Layer Engine
    -- =============================================================================
    -- One dense_layer instance is reused sequentially for all four layers
    --
    -- Runtime configuration selects:
    --     input count
    --     output count
    --     ReLU enable
    --     binary-input optimization
    signal dense_start : std_logic := '0';
    signal dense_done : std_logic;

    signal dense_input_count : natural range 1 to LAYER1_INPUTS := LAYER1_INPUTS;
    signal dense_output_count : natural range 1 to LAYER1_OUTPUTS := LAYER1_OUTPUTS;
    signal dense_apply_relu : std_logic := '1';
    signal dense_binary_input_mode : std_logic := '0';
    signal dense_input_address : natural range 0 to LAYER1_INPUTS - 1;
    signal dense_input_data : data_t;
    -- All output-neuron weights for the current input.
    signal dense_weight_data : weight_array_t(0 to LAYER1_OUTPUTS - 1) := (others => (others => '0'));
    -- All layer outputs become available together.
    signal dense_output_data : data_array_t(0 to LAYER1_OUTPUTS - 1);
    signal dense_output_logit_data : logit_array_t(0 to LAYER1_OUTPUTS - 1);


    -- =============================================================================
    -- Layer-Specific Weight-ROM Input Indexes
    -- =============================================================================
    --
    -- dense_input_address uses the range required by the largest layer:
    --
    --     0 .. 783
    --
    -- Each weight ROM, however, has a smaller legal input-index range.
    --
    -- Dedicated signals prevent a value belonging to another layer from being
    -- applied to an inactive ROM during FSM transitions.
    --
    signal layer1_weight_input_index : natural range 0 to LAYER1_INPUTS - 1 := 0;
    signal layer2_weight_input_index : natural range 0 to LAYER2_INPUTS - 1 := 0;
    signal layer3_weight_input_index : natural range 0 to LAYER3_INPUTS - 1 := 0;
    signal layer4_weight_input_index : natural range 0 to LAYER4_INPUTS - 1 := 0;

    -- =============================================================================
    -- Weight ROMs
    -- =============================================================================
    -- Each layer has its own Quartus-initialized weight ROM
    --
    -- The shared dense engine selects the appropriate ROM according to the
    -- current top-level FSM state
    signal layer1_weight_data : weight_array_t(0 to LAYER1_OUTPUTS - 1);
    signal layer2_weight_data : weight_array_t(0 to LAYER2_OUTPUTS - 1);
    signal layer3_weight_data : weight_array_t(0 to LAYER3_OUTPUTS - 1);
    signal layer4_weight_data : weight_array_t(0 to LAYER4_OUTPUTS - 1);

    -- =============================================================================
    -- ArgMax
    -- =============================================================================
    signal argmax_start : std_logic := '0';
    signal argmax_done : std_logic;
    signal argmax_result : unsigned(3 downto 0);

begin

    -- =============================================================================
    -- Input Buffer
    -- =============================================================================
    -- The input buffer stores 784 one-bit pixels (28 by 28 image)
    -- `read_data` converts the selected pixel to signed `data_t` only when the
    -- dense layer reads it
    input_buffer_inst : entity work.input_buffer
        port map (
            clk => clk,
            rst => rst,
            pixel_in => pixel_in,
            pixel_valid => pixel_valid,
            clear => input_buffer_clear,
            image_ready => image_ready,
            read_address => input_buffer_address,
            read_data => input_buffer_data
        );

        -- =============================================================================
    -- Layer 1 Parallel Weight ROM
    -- =============================================================================

    layer1_rom : entity work.weight_rom
        generic map (
            INPUT_COUNT => LAYER1_INPUTS,
            OUTPUT_COUNT => LAYER1_OUTPUTS,
            INIT_FILE => LAYER1_WEIGHT_INIT_FILE,
            SIM_INIT_FILE => LAYER1_WEIGHT_SIM_FILE
        )
        port map (
            input_index => layer1_weight_input_index,
            weights => layer1_weight_data
        );

    -- =============================================================================
    -- Layer 2 Parallel Weight ROM
    -- =============================================================================

    layer2_rom : entity work.weight_rom
        generic map (
            INPUT_COUNT => LAYER2_INPUTS,
            OUTPUT_COUNT => LAYER2_OUTPUTS,
            INIT_FILE => LAYER2_WEIGHT_INIT_FILE,
            SIM_INIT_FILE => LAYER2_WEIGHT_SIM_FILE
        )
        port map (
            input_index => layer2_weight_input_index,
            weights => layer2_weight_data
        );

    -- =============================================================================
    -- Layer 3 Parallel Weight ROM
    -- =============================================================================

    layer3_rom : entity work.weight_rom
        generic map (
            INPUT_COUNT => LAYER3_INPUTS,
            OUTPUT_COUNT => LAYER3_OUTPUTS,
            INIT_FILE => LAYER3_WEIGHT_INIT_FILE,
            SIM_INIT_FILE => LAYER3_WEIGHT_SIM_FILE
        )
        port map (
            input_index => layer3_weight_input_index,
            weights => layer3_weight_data
        );

    -- =============================================================================
    -- Layer 4 Parallel Weight ROM
    -- =============================================================================

    layer4_rom : entity work.weight_rom
    generic map (
        INPUT_COUNT => LAYER4_INPUTS,
        OUTPUT_COUNT => LAYER4_OUTPUTS,
        INIT_FILE => LAYER4_WEIGHT_INIT_FILE,
        SIM_INIT_FILE => LAYER4_WEIGHT_SIM_FILE
    )
    port map (
        input_index => layer4_weight_input_index,
        weights => layer4_weight_data
    );

    -- =============================================================================
    -- Parallel Dense-Layer Engine
    -- =============================================================================

    dense_layer_inst : entity work.dense_layer
        generic map (
            MAX_INPUTS => LAYER1_INPUTS,
            MAX_OUTPUTS => LAYER1_OUTPUTS
        )
        port map (
            clk => clk,
            rst => rst,
            start => dense_start,
            input_count => dense_input_count,
            output_count => dense_output_count,
            apply_relu => dense_apply_relu,
            binary_input_mode => dense_binary_input_mode,
            input_address => dense_input_address,
            input_data => dense_input_data,
            weight_data => dense_weight_data,
            output_data => dense_output_data,
            output_logit_data => dense_output_logit_data,
            busy => open,
            done => dense_done
        );

    -- =============================================================================
    -- ArgMax
    -- =============================================================================
    argmax_inst : entity work.argmax
        port map (
            clk => clk,
            rst => rst,
            start => argmax_start,
            values => layer4_buffer,
            done => argmax_done,
            class_out => argmax_result
        );

    -- =============================================================================
    -- Weight-ROM Input-Index Multiplexer
    -- =============================================================================
    --
    -- Only the ROM belonging to the active neural-network layer receives the
    -- shared dense-layer input address.
    --
    -- All inactive ROMs remain at input index zero.
    --
    -- This is required because dense_input_address is sized for Layer 1 and can
    -- therefore contain values that are outside the legal index range of the
    -- smaller Layer 2, Layer 3, and Layer 4 ROMs.
    --
    -- Example:
    --
    --     dense_input_address = 63
    --
    -- is valid for Layer 2 and Layer 3, but invalid for Layer 4, whose range is:
    --
    --     0 .. 31
    --
    process(all)
    begin
        -- Safe defaults for all inactive ROMs.
        layer1_weight_input_index <= 0;
        layer2_weight_input_index <= 0;
        layer3_weight_input_index <= 0;
        layer4_weight_input_index <= 0;

        case state is
            when LAYER1 =>
                if dense_input_address < LAYER1_INPUTS then
                    layer1_weight_input_index <= dense_input_address;
                end if;

            when LAYER2 =>
                if dense_input_address < LAYER2_INPUTS then
                    layer2_weight_input_index <= dense_input_address;
                end if;

            when LAYER3 =>
                if dense_input_address < LAYER3_INPUTS then
                    layer3_weight_input_index <= dense_input_address;
                end if;

            when LAYER4 =>
                if dense_input_address < LAYER4_INPUTS then
                    layer4_weight_input_index <= dense_input_address;
                end if;

            when others => null;
        end case;

    end process;

    -- =============================================================================
    -- Dense-Layer Input Multiplexer
    -- =============================================================================
    --
    -- Selects the activation source according to the active neural-network
    -- layer
    --
    -- Layer 1:       one-bit image buffer
    -- Layers 2 .. 4: read previously calculated fixed-point activations
    process(all)
    begin
        dense_input_data <= (others => '0');
        input_buffer_address <= 0;

        case state is
            when LAYER1 =>
                if dense_input_address < LAYER1_INPUTS then
                    input_buffer_address <= dense_input_address;
                    dense_input_data <= input_buffer_data;
                end if;

            when LAYER2 =>
                if dense_input_address < LAYER2_INPUTS then
                    dense_input_data <= layer1_buffer(dense_input_address);
                end if;

            when LAYER3 =>
                if dense_input_address < LAYER3_INPUTS then
                    dense_input_data <= layer2_buffer(dense_input_address);
                end if;

            when LAYER4 =>
                if dense_input_address < LAYER4_INPUTS then
                    dense_input_data <= layer3_buffer(dense_input_address);
                end if;

            when others =>
                null;
        end case;
    end process;



    -- =============================================================================
    -- Parallel Weight-Vector Multiplexer
    -- =============================================================================
    process(all)
    begin
        dense_weight_data <= (others => (others => '0'));

        case state is
            when LAYER1 =>
                for i in 0 to LAYER1_OUTPUTS - 1 loop
                    dense_weight_data(i) <= layer1_weight_data(i);
                end loop;

            when LAYER2 =>
                for i in 0 to LAYER2_OUTPUTS - 1 loop
                    dense_weight_data(i) <= layer2_weight_data(i);
                end loop;

            when LAYER3 =>
                for i in 0 to LAYER3_OUTPUTS - 1 loop
                    dense_weight_data(i) <= layer3_weight_data(i);
                end loop;

            when LAYER4 =>
                for i in 0 to LAYER4_OUTPUTS - 1 loop
                    dense_weight_data(i) <= layer4_weight_data(i);
                end loop;

            when others => null;
        end case;

    end process;

    -- =============================================================================
    -- Top-Level Neural-Network Controller
    -- =============================================================================
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                state <= IDLE;
                input_buffer_clear <= '1';
                input_ready <= '0';
                dense_start <= '0';
                dense_input_count <= LAYER1_INPUTS;
                dense_output_count <= LAYER1_OUTPUTS;
                dense_apply_relu <= '1';
                dense_binary_input_mode <= '0';
                argmax_start <= '0';
                result_valid <= '0';
                predicted_digit <= (others => '0');
            else
                input_buffer_clear <= '0';
                dense_start <= '0';
                argmax_start <= '0';
                result_valid <= '0';
                case state is
                    when IDLE =>
                        input_buffer_clear <= '1';
                        input_ready <= '1';
                        dense_binary_input_mode <= '0';
                        state <= WAIT_FOR_DATA;
                    when WAIT_FOR_DATA =>
                        input_ready <= '1';
                        if image_ready = '1' then
                            input_ready <= '0';
                            dense_input_count <= LAYER1_INPUTS;
                            dense_output_count <= LAYER1_OUTPUTS;
                            dense_apply_relu <= '1';
                            dense_binary_input_mode <= '1';
                            dense_start <= '1';
                            state <= LAYER1;
                        end if;
                    when LAYER1 =>
                        input_ready <= '0';
                        if dense_done = '1' then
                            for i in 0 to LAYER1_OUTPUTS - 1 loop
                                layer1_buffer(i) <= dense_output_data(i);
                            end loop;
                            dense_input_count <= LAYER2_INPUTS;
                            dense_output_count <= LAYER2_OUTPUTS;
                            dense_apply_relu <= '1';
                            dense_binary_input_mode <= '0';
                            dense_start <= '1';
                            state <= LAYER2;
                        end if;
                    when LAYER2 =>
                        if dense_done = '1' then
                            for i in 0 to LAYER2_OUTPUTS - 1 loop
                                layer2_buffer(i) <= dense_output_data(i);
                            end loop;
                            dense_input_count <= LAYER3_INPUTS;
                            dense_output_count <= LAYER3_OUTPUTS;
                            dense_apply_relu <= '1';
                            dense_binary_input_mode <= '0';
                            dense_start <= '1';
                            state <= LAYER3;
                        end if;
                    when LAYER3 =>
                        if dense_done = '1' then
                            for i in 0 to LAYER3_OUTPUTS - 1 loop
                                layer3_buffer(i) <= dense_output_data(i);
                            end loop;
                            dense_input_count <= LAYER4_INPUTS;
                            dense_output_count <= LAYER4_OUTPUTS;
                            dense_apply_relu <= '0';
                            dense_binary_input_mode <= '0';
                            dense_start <= '1';
                            state <= LAYER4;
                        end if;
                    when LAYER4 =>
                        if dense_done = '1' then
                            for i in 0 to LAYER4_OUTPUTS - 1 loop
                                layer4_buffer(i) <= dense_output_logit_data(i);
                            end loop;
                            state <= START_ARGMAX;
                        end if;
                    when START_ARGMAX =>
                        -- Layer-4 buffer was written on the previous clock.
                        --
                        -- ArgMax can now safely consume the new logits.
                        argmax_start <= '1';
                        state <= ARGMAX_STATE;
                    when ARGMAX_STATE =>
                        if argmax_done = '1' then
                            predicted_digit <= argmax_result;
                            state <= OUTPUT_RESULT;
                        end if;
                    when OUTPUT_RESULT =>
                        result_valid <= '1';
                        state <= IDLE;
                end case;
            end if;
        end if;
    end process;

end architecture rtl;