library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.nn_config_pkg.all;
use work.nn_types_pkg.all;

-- =============================================================================
-- Neural-Network Core
-- =============================================================================
--
-- Top-level controller for the sequential MNIST neural-network implementation.
--
-- Only ONE image is processed at a time.
--
-- A new image is accepted only after the previous image has completed all
-- neural-network layers and the classification result has been generated.
--
-- Network topology:
--
--     784 binary input pixels
--              |
--              v
--       Layer 1: 784 -> 64
--              |
--             ReLU
--              |
--              v
--       Layer 2: 64 -> 64
--              |
--             ReLU
--              |
--              v
--       Layer 3: 64 -> 32
--              |
--             ReLU
--              |
--              v
--       Layer 4: 32 -> 10
--              |
--              v
--            ArgMax
--              |
--              v
--       predicted_digit
--
-- Layer 1 Optimization:
--
-- The input_buffer stores each MNIST pixel using only one bit because
-- training.py already binarizes the original grayscale pixels:
--
--     pixel <= 127 -> 0
--     pixel >  127 -> 1
--
-- Therefore the dense-layer engine can bypass the multiplier for Layer 1:
--
--     input = 0 -> contribution = 0
--     input = 1 -> contribution = weight
--
-- The dense_binary_input_mode signal enables this optimization only while
-- Layer 1 is active.
--
-- Top-level Finite State Machine (sequential)
--
--     IDLE
--       |
--       v
--     WAIT_FOR_DATA
--       |
--       | 784 pixels received
--       v
--     LAYER1
--       |
--       v
--     LAYER2
--       |
--       v
--     LAYER3
--       |
--       v
--     LAYER4
--       |
--       v
--     ARGMAX_STATE
--       |
--       v
--     OUTPUT_RESULT
--       |
--       v
--     IDLE
--
-- =============================================================================

entity nn_core is
    port (
        -- Clock and reset signals
        clk : in std_logic;
        rst : in std_logic;
        -- ---------------------------------------------------------------------
        -- Input Pixel Stream
        -- ---------------------------------------------------------------------
        --
        -- pixel_in contains one already-binarized MNIST pixel:
        --
        --     '0' -> original grayscale pixel <= 127
        --     '1' -> original grayscale pixel > 127
        --
        -- pixel_valid must be asserted when pixel_in contains a valid pixel
        pixel_in    : in std_logic;
        pixel_valid : in std_logic;
        -- High while the core can accept pixels for a new image
        input_ready : out std_logic;
        -- ---------------------------------------------------------------------
        -- Classification Output
        -- ---------------------------------------------------------------------
        -- Pulses high when predicted_digit contains a valid classification
        result_valid : out std_logic;
        -- Predicted MNIST digit from 0 to 9
        predicted_digit : out unsigned(3 downto 0)
    );
end entity nn_core;

architecture rtl of nn_core is

    -- =============================================================================
    -- Top-Level State Machine
    -- =============================================================================
    type state_t is (
        IDLE,
        WAIT_FOR_DATA,
        LAYER1,
        LAYER2,
        LAYER3,
        LAYER4,
        ARGMAX_STATE,
        OUTPUT_RESULT
    );
    signal state : state_t := IDLE;

    -- =============================================================================
    -- Input Buffer
    -- =============================================================================
    -- Clears the previously stored image before receiving a new one.
    signal input_buffer_clear : std_logic := '0';
    -- Asserted by input_buffer after all 784 pixels are stored.
    signal image_ready : std_logic;
    -- Address generated by the dense-layer engine when reading Layer 1 inputs.
    signal input_buffer_address : natural range 0 to INPUT_SIZE - 1 := 0;
    -- input_buffer converts the selected one-bit pixel to data_t:
    --
    --     0 -> signed 0
    --     1 -> signed 1
    signal input_buffer_data : data_t;

    -- =============================================================================
    -- Intermediate Activation Buffers
    -- =============================================================================
    --
    -- Layer 1 through Layer 3 outputs are stored as signed fixed-point `data_t`
    -- values
    -- Layer 4 contains the ten output logits used by ArgMax.
    signal layer1_buffer : data_array_t(0 to LAYER1_OUTPUTS - 1) := (others => (others => '0'));
    signal layer2_buffer : data_array_t(0 to LAYER2_OUTPUTS - 1) := (others => (others => '0'));
    signal layer3_buffer : data_array_t(0 to LAYER3_OUTPUTS - 1) := (others => (others => '0'));
    signal layer4_buffer : logit_array_t(0 to LAYER4_OUTPUTS - 1) := (others => (others => '0'));

    -- =============================================================================
    -- Shared Dense-Layer Engine
    -- =============================================================================
    -- One dense_layer instance is reused sequentially for all four layers
    --
    -- Runtime configuration selects:
    --     input count
    --     output count
    --     ReLU enable
    --     binary-input optimization
    signal dense_start : std_logic := '0';
    signal dense_busy : std_logic;
    signal dense_done : std_logic;
    signal dense_input_count : natural range 1 to LAYER1_INPUTS := LAYER1_INPUTS;
    signal dense_output_count : natural range 1 to LAYER1_OUTPUTS := LAYER1_OUTPUTS;
    -- Enable ReLU for Layers 1 through 3
    signal dense_apply_relu : std_logic := '1';
    -- Enable the multiplier bypass only for Layer 1
    signal dense_binary_input_mode : std_logic := '0';
    -- Address of the current dense-layer input
    signal dense_input_address : natural range 0 to LAYER1_INPUTS - 1;
    -- Activation connected to the shared dense-layer input
    signal dense_input_data : data_t;
    -- Address generated for the active weight ROM
    signal dense_weight_address : natural range 0 to (LAYER1_INPUTS * LAYER1_OUTPUTS) - 1;
    -- Weight returned by the currently active ROM
    signal dense_weight_data : weight_t;
    -- Dense-layer output write interface
    signal dense_output_we : std_logic;
    signal dense_output_address : natural range 0 to LAYER1_OUTPUTS - 1;
    signal dense_output_data : data_t;
    signal dense_output_logit_data : logit_t;

    -- =============================================================================
    -- Weight ROMs
    -- =============================================================================
    -- Each layer has its own Quartus-initialized weight ROM
    --
    -- The shared dense engine selects the appropriate ROM according to the
    -- current top-level FSM state
    signal layer1_weight_address : natural range 0 to (LAYER1_INPUTS * LAYER1_OUTPUTS) - 1 := 0;
    signal layer2_weight_address : natural range 0 to (LAYER2_INPUTS * LAYER2_OUTPUTS) - 1 := 0;
    signal layer3_weight_address : natural range 0 to (LAYER3_INPUTS * LAYER3_OUTPUTS) - 1 := 0;
    signal layer4_weight_address : natural range 0 to (LAYER4_INPUTS * LAYER4_OUTPUTS) - 1 := 0;
    signal layer1_weight_data : weight_t;
    signal layer2_weight_data : weight_t;
    signal layer3_weight_data : weight_t;
    signal layer4_weight_data : weight_t;

    -- =============================================================================
    -- ArgMax
    -- =============================================================================
    signal argmax_start : std_logic := '0';
    signal argmax_done : std_logic;
    signal argmax_result : unsigned(3 downto 0);

begin

    -- =============================================================================
    -- Input Buffer
    -- =============================================================================
    -- The input buffer stores 784 one-bit pixels (28 by 28 image)
    -- `read_data` converts the selected pixel to signed `data_t` only when the
    -- dense layer reads it
    input_buffer_inst : entity work.input_buffer
        port map (
            clk => clk,
            rst => rst,
            pixel_in => pixel_in,
            pixel_valid => pixel_valid,
            clear => input_buffer_clear,
            image_ready => image_ready,
            read_address => input_buffer_address,
            read_data => input_buffer_data
        );

    -- =============================================================================
    -- Layer 1 Weight ROM
    -- =============================================================================
    layer1_rom : entity work.weight_rom
        generic map (
            LAYER_ID => 1,
            DEPTH => LAYER1_INPUTS * LAYER1_OUTPUTS
        )
        port map (
            clk => clk,
            address => layer1_weight_address,
            data_out => layer1_weight_data
        );

    -- =============================================================================
    -- Layer 2 Weight ROM
    -- =============================================================================
    layer2_rom : entity work.weight_rom
        generic map (
            LAYER_ID => 2,
            DEPTH => LAYER2_INPUTS * LAYER2_OUTPUTS
        )
        port map (
            clk => clk,
            address => layer2_weight_address,
            data_out => layer2_weight_data
        );

    -- =============================================================================
    -- Layer 3 Weight ROM
    -- =============================================================================
    layer3_rom : entity work.weight_rom
        generic map (
            LAYER_ID => 3,
            DEPTH => LAYER3_INPUTS * LAYER3_OUTPUTS
        )
        port map (
            clk => clk,
            address => layer3_weight_address,
            data_out => layer3_weight_data
        );

    -- =============================================================================
    -- Layer 4 Weight ROM
    -- =============================================================================
    layer4_rom : entity work.weight_rom
        generic map (
            LAYER_ID => 4,
            DEPTH => LAYER4_INPUTS * LAYER4_OUTPUTS
        )
        port map (
            clk => clk,
            address => layer4_weight_address,
            data_out => layer4_weight_data
        );

    -- =============================================================================
    -- Shared Dense-Layer Engine
    -- =============================================================================
    dense_layer_inst : entity work.dense_layer
        generic map (
            MAX_INPUTS => LAYER1_INPUTS,
            MAX_OUTPUTS => LAYER1_OUTPUTS
        )
        port map (
            clk => clk,
            rst => rst,
            start => dense_start,
            input_count => dense_input_count,
            output_count => dense_output_count,
            apply_relu => dense_apply_relu,
            binary_input_mode => dense_binary_input_mode,
            input_address => dense_input_address,
            input_data => dense_input_data,
            weight_address => dense_weight_address,
            weight_data => dense_weight_data,
            output_write_enable => dense_output_we,
            output_address      => dense_output_address,
            output_data         => dense_output_data,
            output_logit_data   => dense_output_logit_data,
            busy => dense_busy,
            done => dense_done
        );

    -- =============================================================================
    -- ArgMax
    -- =============================================================================
    argmax_inst : entity work.argmax
        port map (
            clk => clk,
            rst => rst,
            start => argmax_start,
            values => layer4_buffer,
            done => argmax_done,
            class_out => argmax_result
        );

    -- =============================================================================
    -- Dense-Layer Input Multiplexer
    -- =============================================================================
    --
    -- Selects the activation source according to the active neural-network
    -- layer
    --
    -- Layer 1:       one-bit image buffer
    -- Layers 2 .. 4: read previously calculated fixed-point activations
    process(state, dense_input_address, input_buffer_data, layer1_buffer, layer2_buffer, layer3_buffer)
    begin
        dense_input_data <= (others => '0');
        input_buffer_address <= 0;

        case state is
            when LAYER1 =>
                if dense_input_address < LAYER1_INPUTS then
                    input_buffer_address <= dense_input_address;
                    dense_input_data <= input_buffer_data;
                end if;

            when LAYER2 =>
                if dense_input_address < LAYER2_INPUTS then
                    dense_input_data <= layer1_buffer(dense_input_address);
                end if;

            when LAYER3 =>
                if dense_input_address < LAYER3_INPUTS then
                    dense_input_data <= layer2_buffer(dense_input_address);
                end if;

            when LAYER4 =>
                if dense_input_address < LAYER4_INPUTS then
                    dense_input_data <= layer3_buffer(dense_input_address);
                end if;

            when others =>
                dense_input_data <= (others => '0');
        end case;
    end process;

    -- =============================================================================
    -- Weight-ROM Address Multiplexer
    -- =============================================================================
    -- Only the ROM corresponding to the active layer receives
    -- dense_weight_address
    --
    -- All inactive ROM addresses remain zero
    process(state, dense_weight_address)
    begin
        layer1_weight_address <= 0;
        layer2_weight_address <= 0;
        layer3_weight_address <= 0;
        layer4_weight_address <= 0;

        case state is
            when LAYER1 =>
                if dense_weight_address < (LAYER1_INPUTS * LAYER1_OUTPUTS) then
                    layer1_weight_address <= dense_weight_address;
                end if;

            when LAYER2 =>
                if dense_weight_address < (LAYER2_INPUTS * LAYER2_OUTPUTS) then
                    layer2_weight_address <= dense_weight_address;
                end if;

            when LAYER3 =>
                if dense_weight_address < (LAYER3_INPUTS * LAYER3_OUTPUTS) then
                    layer3_weight_address <= dense_weight_address;
                end if;

            when LAYER4 =>
                if dense_weight_address < (LAYER4_INPUTS * LAYER4_OUTPUTS) then
                    layer4_weight_address <= dense_weight_address;
                end if;

            when others =>
                null;
        end case;
    end process;

    -- =============================================================================
    -- Weight-ROM Data Multiplexer
    -- =============================================================================
    process(state, layer1_weight_data, layer2_weight_data, layer3_weight_data, layer4_weight_data)
    begin
        dense_weight_data <= (others => '0');
        case state is
            when LAYER1 =>
                dense_weight_data <= layer1_weight_data;
            when LAYER2 =>
                dense_weight_data <= layer2_weight_data;
            when LAYER3 =>
                dense_weight_data <= layer3_weight_data;
            when LAYER4 =>
                dense_weight_data <= layer4_weight_data;
            when others =>
                dense_weight_data <= (others => '0');
        end case;
    end process;

    -- =============================================================================
    -- Store Dense-Layer Outputs
    -- =============================================================================
    -- The shared dense engine generates one completed neuron value at a time
    --
    -- Store that value into the buffer corresponding to the active layer
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                layer1_buffer <= (others => (others => '0'));
                layer2_buffer <= (others => (others => '0'));
                layer3_buffer <= (others => (others => '0'));
                layer4_buffer <= (others => (others => '0'));

            elsif dense_output_we = '1' then
                case state is
                    when LAYER1 =>
                        layer1_buffer(dense_output_address) <= dense_output_data;

                    when LAYER2 =>
                        layer2_buffer(dense_output_address) <= dense_output_data;

                    when LAYER3 =>
                        layer3_buffer(dense_output_address) <= dense_output_data;

                    when LAYER4 =>
                        layer4_buffer(dense_output_address) <= dense_output_logit_data;

                    when others =>
                        null;
                end case;
            end if;
        end if;
    end process;

    -- =============================================================================
    -- Top-Level Neural-Network Controller
    -- =============================================================================
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                state <= IDLE;
                input_buffer_clear <= '1';
                input_ready <= '0';
                dense_start <= '0';
                dense_input_count <= LAYER1_INPUTS;
                dense_output_count <= LAYER1_OUTPUTS;
                dense_apply_relu <= '1';
                dense_binary_input_mode <= '0';
                argmax_start <= '0';
                result_valid <= '0';
                predicted_digit <= (others => '0');
            else
                input_buffer_clear <= '0';
                dense_start <= '0';
                argmax_start <= '0';
                result_valid <= '0';
                case state is
                    when IDLE =>
                        input_buffer_clear <= '1';
                        input_ready <= '1';
                        dense_binary_input_mode <= '0';
                        state <= WAIT_FOR_DATA;
                    when WAIT_FOR_DATA =>
                        input_ready <= '1';
                        if image_ready = '1' then
                            input_ready <= '0';
                            dense_input_count <= LAYER1_INPUTS;
                            dense_output_count <= LAYER1_OUTPUTS;
                            dense_apply_relu <= '1';
                            dense_binary_input_mode <= '1';
                            dense_start <= '1';
                            state <= LAYER1;
                        end if;
                    when LAYER1 =>
                        input_ready <= '0';
                        if dense_done = '1' then
                            dense_input_count <= LAYER2_INPUTS;
                            dense_output_count <= LAYER2_OUTPUTS;
                            dense_apply_relu <= '1';
                            dense_binary_input_mode <= '0';
                            dense_start <= '1';
                            state <= LAYER2;
                        end if;
                    when LAYER2 =>
                        if dense_done = '1' then
                            dense_input_count <= LAYER3_INPUTS;
                            dense_output_count <= LAYER3_OUTPUTS;
                            dense_apply_relu <= '1';
                            dense_binary_input_mode <= '0';
                            dense_start <= '1';
                            state <= LAYER3;
                        end if;
                    when LAYER3 =>
                        if dense_done = '1' then
                            dense_input_count <= LAYER4_INPUTS;
                            dense_output_count <= LAYER4_OUTPUTS;
                            dense_apply_relu <= '0';
                            dense_binary_input_mode <= '0';
                            dense_start <= '1';
                            state <= LAYER4;
                        end if;
                    when LAYER4 =>
                        if dense_done = '1' then
                            argmax_start <= '1';
                            state <= ARGMAX_STATE;
                        end if;
                    when ARGMAX_STATE =>
                        if argmax_done = '1' then
                            predicted_digit <= argmax_result;
                            state <= OUTPUT_RESULT;
                        end if;
                    when OUTPUT_RESULT =>
                        result_valid <= '1';
                        state <= IDLE;
                end case;
            end if;
        end if;
    end process;

end architecture rtl;